// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "天河国云",
            "url": "http://www.swagger.io/support",
            "email": "624796905@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applicationChain/exitCrossChainChannel": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "退出跨链通道",
                "parameters": [
                    {
                        "description": "退出跨链通道参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ExitCrossChainChannelReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/applicationChain/getAllApplicationChain": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "获取所有应用链",
                "parameters": [
                    {
                        "description": "获取所有应用链参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetAllApplicationChainReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "$ref": "#/definitions/model.ApplicationChain"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/applicationChain/getAllApplicationChainName": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "获取所有应用链名称和Id",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ApplicationChainName"
                            }
                        }
                    }
                }
            }
        },
        "/applicationChain/getApplicationChainByChannelId/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "根据跨链通道Id获取所有应用链",
                "parameters": [
                    {
                        "type": "string",
                        "description": "跨链通道id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ApplicationChain"
                            }
                        }
                    }
                }
            }
        },
        "/applicationChain/getApplicationChainByGatewayId": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "根据网关Id获取所有应用链",
                "parameters": [
                    {
                        "description": "获取应用链参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetAppChainByGatewayIdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/model.ApplicationChain"
                        }
                    }
                }
            }
        },
        "/applicationChain/getApplicationChainById/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "获取单个应用链详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用链id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.GetAppChainByIdResp"
                        }
                    }
                }
            }
        },
        "/applicationChain/getApplicationChainInfo": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "获取登录应用链详情信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/model.ApplicationChain"
                        }
                    }
                }
            }
        },
        "/applicationChain/joinCrossChainChannel": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "加入跨链通道",
                "parameters": [
                    {
                        "description": "加入跨链通道参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.JoinCrossChainChannelReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/applicationChain/setApplicationChain": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.applicationChain"
                ],
                "summary": "冻结/解冻应用链",
                "parameters": [
                    {
                        "description": "冻结应用链参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SetAppChainReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/crossChainChannel/auditAppChainJoinChannel": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.crossChainChannel"
                ],
                "summary": "跨链通道审核应用锁加入/退出通道",
                "parameters": [
                    {
                        "description": "获取跨链通道参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AuditAppChainJoinChannelReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/crossChainChannel/getAllCrossChainChannel": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.crossChainChannel"
                ],
                "summary": "获取所有跨链通道信息",
                "parameters": [
                    {
                        "description": "获取所有跨链通道参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetAllCrossChainChannelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "$ref": "#/definitions/model.CrossChainChannel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/crossChainChannel/getApplyApplicationChain/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.crossChainChannel"
                ],
                "summary": "获取所有申请应用链",
                "parameters": [
                    {
                        "type": "string",
                        "description": "跨链通道id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/crossChainChannel/getCrossChainChannelByAppChainId": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.crossChainChannel"
                ],
                "summary": "根据应用链Id获取所有跨链通道",
                "parameters": [
                    {
                        "description": "获取跨链通道参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetAllByAppChainIdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "$ref": "#/definitions/model.CrossChainChannel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/crossChainChannel/getCrossChainChannelByGatewayId": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.crossChainChannel"
                ],
                "summary": "根据网关Id获取所有跨链通道",
                "parameters": [
                    {
                        "description": "获取跨链通道参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetAppChainByGatewayIdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "$ref": "#/definitions/model.CrossChainChannel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/crossChainChannel/getCrossChainChannelById/{id}": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.crossChainChannel"
                ],
                "summary": "获取单个跨链通道详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "跨链通道id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/model.CrossChainTransaction"
                        }
                    }
                }
            }
        },
        "/crossChainChannel/getCrossChainChannelInfo": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.crossChainChannel"
                ],
                "summary": "获取登录跨链通道详情信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/model.CrossChainChannel"
                        }
                    }
                }
            }
        },
        "/gateway/getAllGateway": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.gateway"
                ],
                "summary": "获取所有网关信息",
                "parameters": [
                    {
                        "description": "获取所有网关参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetAllGatewayReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "$ref": "#/definitions/model.Gateway"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/gateway/getAllGatewayName": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.gateway"
                ],
                "summary": "获取所有网关的名称和Id信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.GatewayName"
                            }
                        }
                    }
                }
            }
        },
        "/gateway/getGatewayById/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.gateway"
                ],
                "summary": "获取单个网关详情信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "网关id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.GetByIdResp"
                        }
                    }
                }
            }
        },
        "/gateway/getGatewayInfo": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.gateway"
                ],
                "summary": "获取登录网关详情信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/model.Gateway"
                        }
                    }
                }
            }
        },
        "/gateway/getGatewaySysResources/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.gateway"
                ],
                "summary": "获取物理网关服务器系统资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "网关Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.GetSysResourcesResp"
                        }
                    }
                }
            }
        },
        "/gateway/setGateway": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.gateway"
                ],
                "summary": "冻结/解冻网关",
                "parameters": [
                    {
                        "description": "冻结/解冻网关参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SetGatewayReq"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/transaction/createTransaction": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.transaction"
                ],
                "summary": "创建事务",
                "parameters": [
                    {
                        "description": "创建事务参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateTransactionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseMsg"
                        }
                    }
                }
            }
        },
        "/transaction/getAllTransaction": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.transaction"
                ],
                "summary": "获取所有事务",
                "parameters": [
                    {
                        "description": "获取所有事务参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PageInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "$ref": "#/definitions/model.CrossChainTransaction"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/auditUserRegister": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "审核用户注册",
                "parameters": [
                    {
                        "description": "审核用户注册参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AuditUserRegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResp"
                        }
                    }
                }
            }
        },
        "/user/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResp"
                        }
                    }
                }
            }
        },
        "/user/getAllTotals": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "获取资源总数量",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.GetAllTotalsResp"
                        }
                    }
                }
            }
        },
        "/user/getAllUser": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "获取所有玩家信息",
                "parameters": [
                    {
                        "description": "获取用户详细信息参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetAllUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/getUserById/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "获取用户详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.GetUserByIdResp"
                        }
                    }
                }
            }
        },
        "/user/getUserInfo": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "获取登录账号信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.LoginResp"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResp"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "注册账号",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResp"
                        }
                    }
                }
            }
        },
        "/user/resetPassword": {
            "put": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "重置密码参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResp"
                        }
                    }
                }
            }
        },
        "/user/updatePassword": {
            "put": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdatePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResp"
                        }
                    }
                }
            }
        },
        "/user/updateUserInfo": {
            "put": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API.user"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "description": "用户信息参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateUserInfoReq"
                        }
                    },
                    {
                        "description": "修改用户信息参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserInfoMsg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{}}",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ApplicationChain": {
            "type": "object",
            "properties": {
                "app_chain_name": {
                    "description": "应用链名称",
                    "type": "string"
                },
                "consensus_mechanism": {
                    "description": "共识机制",
                    "type": "string"
                },
                "contract_type": {
                    "description": "合约类型",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "cross_chain_technology": {
                    "description": "支持的跨链技术",
                    "type": "string"
                },
                "gateway_id": {
                    "description": "网关Id",
                    "type": "integer"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "logo": {
                    "description": "应用链Logo",
                    "type": "string"
                },
                "rpc_url": {
                    "description": "应用链RPC",
                    "type": "string"
                },
                "status": {
                    "description": "应用链状态(1:正常 2:异常 3.冻结)",
                    "type": "integer"
                },
                "user_id": {
                    "description": "用户Id",
                    "type": "integer"
                }
            }
        },
        "model.ApplicationChainName": {
            "type": "object",
            "properties": {
                "app_chain_name": {
                    "description": "应用链名称",
                    "type": "string"
                },
                "id": {
                    "description": "应用链Id",
                    "type": "integer"
                }
            }
        },
        "model.CrossChainChannel": {
            "type": "object",
            "properties": {
                "application_chain_ids": {
                    "description": "支持的应用链Id",
                    "type": "string"
                },
                "bandwidth": {
                    "description": "带宽",
                    "type": "integer"
                },
                "channel_grade": {
                    "description": "通道密级",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "cross_chain_channel_name": {
                    "description": "跨链通道名称",
                    "type": "string"
                },
                "exit_app_chain_ids": {
                    "description": "申请退出的应用链Id",
                    "type": "string"
                },
                "gateway_ids": {
                    "description": "网关Ids",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "join_app_chain_ids": {
                    "description": "申请加入的应用链Id",
                    "type": "string"
                },
                "status": {
                    "description": "跨链通道状态(1:正常 2:异常 3.冻结)",
                    "type": "integer"
                },
                "user_id": {
                    "description": "用户Id",
                    "type": "integer"
                }
            }
        },
        "model.CrossChainTransaction": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "动作(1:读 2:写)",
                    "type": "integer"
                },
                "channel_name": {
                    "description": "通道名称",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "gateway_ids": {
                    "description": "网关Id",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "request_user_id": {
                    "description": "跨链请求发起用户标识",
                    "type": "string"
                },
                "source_app_chain_contract": {
                    "description": "来源链合约名称",
                    "type": "string"
                },
                "source_app_chain_id": {
                    "description": "来源链标识",
                    "type": "string"
                },
                "status": {
                    "description": "状态(1:成功 2:失败)",
                    "type": "integer"
                },
                "target_app_chain_contract": {
                    "description": "目标链合约名称",
                    "type": "string"
                },
                "target_app_chain_id": {
                    "description": "目标链标识",
                    "type": "string"
                },
                "transaction_id": {
                    "description": "跨链交易标识",
                    "type": "string"
                },
                "transaction_proof": {
                    "description": "跨链交易证明凭证",
                    "type": "string"
                },
                "transaction_receipt": {
                    "description": "跨链交易回执",
                    "type": "string"
                },
                "transaction_time": {
                    "description": "跨链交易时间",
                    "type": "string"
                }
            }
        },
        "model.Gateway": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "gateway_grade": {
                    "description": "网关密级",
                    "type": "string"
                },
                "gateway_name": {
                    "description": "网关名称",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "ip": {
                    "description": "网关Ip地址",
                    "type": "string"
                },
                "province": {
                    "description": "省份",
                    "type": "string"
                },
                "status": {
                    "description": "网关状态(1:正常 2:异常 3.冻结)",
                    "type": "integer"
                },
                "unit": {
                    "description": "所属机构",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户Id",
                    "type": "integer"
                }
            }
        },
        "model.GatewayName": {
            "type": "object",
            "properties": {
                "gateway_name": {
                    "description": "网关名称",
                    "type": "string"
                },
                "id": {
                    "description": "网关Id",
                    "type": "integer"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "contact_name": {
                    "description": "联系人姓名",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "head_portrait": {
                    "description": "头像",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "identity": {
                    "description": "身份",
                    "type": "integer"
                },
                "mail": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile_number": {
                    "description": "手机号码",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "opinion": {
                    "description": "审核意见",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "status": {
                    "description": "状态(1.审核中 2.审核通过 3.审核拒绝)",
                    "type": "integer"
                },
                "unit": {
                    "description": "用户单位",
                    "type": "string"
                }
            }
        },
        "request.AuditAppChainJoinChannelReq": {
            "type": "object",
            "properties": {
                "app_chain_id": {
                    "description": "应用链Id",
                    "type": "integer"
                },
                "types": {
                    "description": "加入/退出 1:加入 2:退出",
                    "type": "integer"
                }
            }
        },
        "request.AuditUserRegisterReq": {
            "type": "object",
            "properties": {
                "opinion": {
                    "description": "审核意见",
                    "type": "string"
                },
                "passed": {
                    "description": "是否通过 2:通过 3:拒绝",
                    "type": "integer"
                },
                "user_id": {
                    "description": "玩家Id",
                    "type": "integer"
                }
            }
        },
        "request.CreateTransactionReq": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "动作(1:读 2:写)",
                    "type": "integer"
                },
                "channel_name": {
                    "description": "通道名称",
                    "type": "string"
                },
                "gateway_ids": {
                    "description": "网关Id",
                    "type": "string"
                },
                "request_user_id": {
                    "description": "跨链请求发起用户标识",
                    "type": "string"
                },
                "source_app_chain_contract": {
                    "description": "来源链合约名称",
                    "type": "string"
                },
                "source_app_chain_id": {
                    "description": "来源链标识",
                    "type": "string"
                },
                "status": {
                    "description": "状态(1:成功 2:失败)",
                    "type": "integer"
                },
                "target_app_chain_contract": {
                    "description": "目标链合约名称",
                    "type": "string"
                },
                "target_app_chain_id": {
                    "description": "目标链标识",
                    "type": "string"
                },
                "transaction_id": {
                    "description": "跨链交易标识",
                    "type": "string"
                },
                "transaction_proof": {
                    "description": "跨链交易证明凭证",
                    "type": "string"
                },
                "transaction_receipt": {
                    "description": "跨链交易回执",
                    "type": "string"
                },
                "transaction_time": {
                    "description": "跨链交易时间",
                    "type": "string"
                }
            }
        },
        "request.ExitCrossChainChannelReq": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "description": "跨链通道Id",
                    "type": "integer"
                }
            }
        },
        "request.Filter": {
            "type": "object",
            "properties": {
                "column": {
                    "description": "列",
                    "type": "string"
                },
                "operator": {
                    "description": "运算符",
                    "type": "string"
                },
                "value": {
                    "description": "值"
                }
            }
        },
        "request.GetAllApplicationChainReq": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Filter"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "request.GetAllByAppChainIdReq": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "应用链Id",
                    "type": "integer"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "request.GetAllCrossChainChannelReq": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Filter"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "request.GetAllGatewayReq": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Filter"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "request.GetAllUserReq": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Filter"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "request.GetAppChainByGatewayIdReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "request.JoinCrossChainChannelReq": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "description": "跨链通道Id",
                    "type": "integer"
                }
            }
        },
        "request.LoginReq": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "request.PageInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "request.RegisterReq": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "account_type": {
                    "description": "账号类型 1:网关管理员 2.应用链管理员 3.跨链通道管理员",
                    "type": "integer"
                },
                "app_chain_name": {
                    "description": "应用链名称",
                    "type": "string"
                },
                "application_chain_ids": {
                    "description": "支持的应用链Id",
                    "type": "string"
                },
                "bandwidth": {
                    "description": "带宽",
                    "type": "integer"
                },
                "channel_grade": {
                    "description": "通道密级",
                    "type": "string"
                },
                "consensus_mechanism": {
                    "description": "共识机制",
                    "type": "string"
                },
                "contact_name": {
                    "description": "联系人姓名",
                    "type": "string"
                },
                "contract_type": {
                    "description": "合约类型",
                    "type": "string"
                },
                "cross_chain_channel_name": {
                    "description": "跨链通道名称",
                    "type": "string"
                },
                "cross_chain_technology": {
                    "description": "支持的跨链技术",
                    "type": "string"
                },
                "gateway_grade": {
                    "description": "网关密级",
                    "type": "string"
                },
                "gateway_id": {
                    "description": "网关Id",
                    "type": "integer"
                },
                "gateway_ids": {
                    "description": "网关Ids",
                    "type": "string"
                },
                "gateway_name": {
                    "description": "网关名称",
                    "type": "string"
                },
                "head_portrait": {
                    "description": "头像",
                    "type": "string"
                },
                "ip": {
                    "description": "网关Ip地址",
                    "type": "string"
                },
                "logo": {
                    "description": "应用链Logo",
                    "type": "string"
                },
                "mail": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile_number": {
                    "description": "手机号码",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "province": {
                    "description": "省份",
                    "type": "string"
                },
                "rpc_url": {
                    "description": "应用链RPC",
                    "type": "string"
                },
                "unit": {
                    "description": "用户单位",
                    "type": "string"
                }
            }
        },
        "request.ResetPasswordReq": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "新密码",
                    "type": "string"
                },
                "user_id": {
                    "description": "玩家Id",
                    "type": "integer"
                }
            }
        },
        "request.SetAppChainReq": {
            "type": "object",
            "properties": {
                "app_chain_id": {
                    "description": "应用链Id",
                    "type": "integer"
                },
                "status": {
                    "description": "应用链状态 1:解冻 3:冻结",
                    "type": "integer"
                }
            }
        },
        "request.SetGatewayReq": {
            "type": "object",
            "properties": {
                "gateway_id": {
                    "description": "网关Id",
                    "type": "integer"
                },
                "status": {
                    "description": "网关状态 1:解冻 3:冻结",
                    "type": "integer"
                }
            }
        },
        "request.UpdatePasswordReq": {
            "type": "object",
            "properties": {
                "new_password": {
                    "description": "新密码",
                    "type": "string"
                },
                "old_password": {
                    "description": "旧密码",
                    "type": "string"
                }
            }
        },
        "request.UpdateUserInfoReq": {
            "type": "object",
            "properties": {
                "user_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.UserInfo"
                    }
                }
            }
        },
        "request.UserInfo": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "字符串",
                    "type": "string"
                },
                "value": {
                    "description": "值"
                }
            }
        },
        "request.UserInfoMsg": {
            "type": "object",
            "properties": {
                "head_portrait": {
                    "description": "头像",
                    "type": "string"
                },
                "mail": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile_number": {
                    "description": "手机号码",
                    "type": "string"
                },
                "name": {
                    "description": "联系人姓名",
                    "type": "string"
                }
            }
        },
        "response.EmptyResp": {
            "type": "object"
        },
        "response.GetAllTotalsResp": {
            "type": "object",
            "properties": {
                "app_chain": {
                    "description": "应用链数量",
                    "type": "integer"
                },
                "cross_chain_channel": {
                    "description": "跨链通道数量",
                    "type": "integer"
                },
                "gateway": {
                    "description": "网关数量",
                    "type": "integer"
                },
                "transaction": {
                    "description": "跨链事务数量",
                    "type": "integer"
                }
            }
        },
        "response.GetAppChainByIdResp": {
            "type": "object",
            "properties": {
                "app_chain_name": {
                    "description": "应用链名称",
                    "type": "string"
                },
                "consensus_mechanism": {
                    "description": "共识机制",
                    "type": "string"
                },
                "contact_name": {
                    "description": "联系人姓名",
                    "type": "string"
                },
                "contract_type": {
                    "description": "合约类型",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "cross_chain_technology": {
                    "description": "支持的跨链技术",
                    "type": "string"
                },
                "gateway_id": {
                    "description": "网关Id",
                    "type": "integer"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "logo": {
                    "description": "应用链Logo",
                    "type": "string"
                },
                "mail": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile_number": {
                    "description": "手机号码",
                    "type": "string"
                },
                "rpc_url": {
                    "description": "应用链RPC",
                    "type": "string"
                },
                "status": {
                    "description": "应用链状态(1:正常 2:异常 3.冻结)",
                    "type": "integer"
                },
                "unit": {
                    "description": "用户单位",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户Id",
                    "type": "integer"
                }
            }
        },
        "response.GetByIdResp": {
            "type": "object",
            "properties": {
                "contact_name": {
                    "description": "联系人姓名",
                    "type": "string"
                },
                "gateway_grade": {
                    "description": "网关密级",
                    "type": "string"
                },
                "gateway_ip": {
                    "description": "网关Ip地址",
                    "type": "string"
                },
                "gateway_name": {
                    "description": "网关名称",
                    "type": "string"
                },
                "gateway_status": {
                    "description": "网关状态",
                    "type": "integer"
                },
                "province": {
                    "description": "所属省份",
                    "type": "string"
                },
                "unit": {
                    "description": "用户单位",
                    "type": "string"
                }
            }
        },
        "response.GetSysResourcesResp": {
            "type": "object",
            "properties": {
                "total_bandwidth": {
                    "description": "总带宽使用率",
                    "type": "integer"
                },
                "total_cpu": {
                    "description": "总cpu使用率",
                    "type": "integer"
                },
                "total_memory": {
                    "description": "总内存使用率",
                    "type": "integer"
                },
                "use_bandwidth": {
                    "description": "使用带宽使用率",
                    "type": "integer"
                },
                "use_cpu": {
                    "description": "使用cpu使用率",
                    "type": "integer"
                },
                "use_memory": {
                    "description": "使用内存使用率",
                    "type": "integer"
                }
            }
        },
        "response.GetUserByIdResp": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "contact_name": {
                    "description": "联系人姓名",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "head_portrait": {
                    "description": "头像",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "identity": {
                    "description": "身份",
                    "type": "integer"
                },
                "mail": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile_number": {
                    "description": "手机号码",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "opinion": {
                    "description": "审核意见",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "status": {
                    "description": "状态(1.审核中 2.审核通过 3.审核拒绝)",
                    "type": "integer"
                },
                "unit": {
                    "description": "用户单位",
                    "type": "string"
                },
                "value": {}
            }
        },
        "response.LoginResp": {
            "type": "object",
            "properties": {
                "identity": {
                    "description": "身份Id(1.云平台管理员 2.网关管理员 3.应用链管理员 4.通道管理员)",
                    "type": "integer"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                }
            }
        },
        "response.PageResult": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "数据"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "页数",
                    "type": "integer"
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "response.ResponseMsg": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "返回码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据"
                },
                "message": {
                    "description": "返回信息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:10010",
	BasePath:         "192.168.1.45:10010",
	Schemes:          []string{},
	Title:            "跨链云平台服务接口文档",
	Description:      "跨链云平台服务接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
