basePath: /
definitions:
  request.LoginReq:
    properties:
      account:
        description: 账号
        type: string
      password:
        description: 密码
        type: string
    type: object
  request.RegisterReq:
    properties:
      account:
        description: 账号
        type: string
      account_type:
        description: 账号类型 1:网关管理员 2.应用链管理员 3.跨链通道管理员
        type: integer
      contact_name:
        description: 联系人姓名
        type: string
      head_portrait:
        description: 头像
        type: string
      mail:
        description: 邮箱
        type: string
      mobile_number:
        description: 手机号码
        type: string
      name:
        description: 名称
        type: string
      password:
        description: 密码
        type: string
      unit:
        description: 用户单位
        type: string
    type: object
  response.EmptyResp:
    type: object
host: localhost:8888
info:
  contact:
    email: 624796905@qq.com
    url: http://www.swagger.io/support
  description: 文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 文档
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginReq'
      produces:
      - application/json
      responses: {}
      summary: 登录
      tags:
      - API.user
  /user/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"ok","data":{}}'
          schema:
            $ref: '#/definitions/response.EmptyResp'
      security:
      - LoginToken: []
      summary: 登出
      tags:
      - API.user
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterReq'
      produces:
      - application/json
      responses: {}
      summary: 注册账号
      tags:
      - API.user
swagger: "2.0"
